### ISSUE TITLE
Toolbar shows 00:60 instead of 01:00

### ISSUE THREAD

**Issue by wymiatacz** [pragha-music-player/pragha#103]
Elapsed time:
> 00:59 -> 00:60 -> 01:01

instead of
> 00:59 -> 01:00 -> 01:01

**Comment by matiasdelellis** [comment]
Ohh.. Thanks.. :disappointed:

**Comment by matiasdelellis** [comment]
Sure the last of your worries, but I chose to start fix it .. :smiley: 

Thank you very much for the reports!. :wink:
