### ISSUE TITLE
Playback options on file opening

### ISSUE THREAD

**Issue by nick87720z** [pragha-music-player/pragha#107]
In my expierience it is first player, which just adds opened file, but doesn't start playback. Some players (smplayer) have similar action, but not as primary action.
I guess, there might be some options, allowing to choose or combine both ways:
- "Play opened file" with suboption "Only if nothing playing" - make sence if someone listens a playlist, but when nothing playing, why not to start new added file?

Additionally i thought about option "Replace playlist", but who might want to remove all, previously added :/

**Comment by matiasdelellis** [comment]
Hi @nick87720z 
Sorry the delay.. Whell, :+1: to the option but need to keep the dialog as clean as possible..

Maybe can add the options in the preferences dialog. And also remove the add files recuribily form the dialog.. :wink:

**Comment by nick87720z** [comment]
I'm thinking about, where to place new options group. Most matching (or yet least unmatching) might be common group. I'm unsure about cleanless principe, they usually follow.... 
Common tab has already 3 groups. I guess, yet another 4-th group should not make it complex :).
Also thought about Audio group. Currently there is only one group - Output device selection... Btw, appart of this bug, how about to rename Audio group name to Ouput?

**Comment by nick87720z** [comment]
This group. It might be combobox or just radio group. If too much groups, they might be foldable, even folded by default...

**On file opening**
*- Just add to playlist
*- Add and play
*- Play if nothing playling
