### ISSUE TITLE
Fix vertical placement of menu button

### ISSUE THREAD

**Issue by nick87720z** [pragha-music-player/pragha#108]
How it looks now:
![pragha-1 3 3](https://cloud.githubusercontent.com/assets/3896190/18655566/6c52604e-7f03-11e6-8c4b-0bd2a5a38dcf.png)

**Comment by matiasdelellis** [comment]
Hi @nick87720z 
You're right ... As It is very dependent on the theme used we will never fix .. :disappointed: 

Now also comment on the pull request.. :wink:

**Comment by matiasdelellis** [comment]
Well, Also fix a placement when show the album art with a huge size.. :wink: 

Thanks.
