### ISSUE TITLE
Grilo 0.3.x not recognized by configure

### ISSUE THREAD

**Issue by GvMariani** [pragha-music-player/pragha#115]
Trying to build pragha 1.3.3 for upcoming Rosa Linux 2016.1 (a Mageia / OpenMandriva sibiling); the distro updated the grilo library to the release 0.3.2 and pragha does not find it because configure.ac has hard-coded library package name as "grilo-0.2", while now it is "grilo-0.3".
Hence this issue is similar to the #82 (btw I'm hitting also this one with rygel-server-2.6).

I would like to patch configure.ac and have it finding the installed grilo-0.3 library (and rygel-server-2.6) but then the rebuilding of configure fails (see next issue).

**Comment by matiasdelellis** [comment]
Maybe is time to update, but meanwhile..

http://pkgs.fedoraproject.org/cgit/rpms/pragha.git/commit/?id=a9915e130fcf0a01e9341ea8e18bf2431a3e058d

**Comment by matiasdelellis** [comment]
Fixed--
