### ISSUE TITLE
Doing autoreconf -vfi fails with automake 1.15 and autoconf 2.69

### ISSUE THREAD

**Issue by GvMariani** [pragha-music-player/pragha#116]
Trying to workaround issues #82 and #115 for pragha 1.3.3 by patching the configure.ac file and regenerating configure.
I'm doing an "autoreconf -vfi", but it fails with a bunch of errors:
*************************************************
Makefile.am:6: error: HAVE_LIBPEAS does not appear in AM_CONDITIONAL
plugins/acoustid/Makefile.am:40: error: HAVE_GSTREAMER_AUDIO does not appear in AM_CONDITIONAL
plugins/acoustid/Makefile.am:45: error: HAVE_LIBXFCE4UI does not appear in AM_CONDITIONAL
plugins/acoustid/Makefile.am: installing './depcomp'
plugins/cdrom/Makefile.am:44: error: HAVE_GSTREAMER_AUDIO does not appear in AM_CONDITIONAL
plugins/cdrom/Makefile.am:49: error: HAVE_LIBXFCE4UI does not appear in AM_CONDITIONAL
plugins/devices/Makefile.am:66: error: HAVE_GSTREAMER_AUDIO does not appear in AM_CONDITIONAL
plugins/devices/Makefile.am:71: error: HAVE_LIBXFCE4UI does not appear in AM_CONDITIONAL
plugins/dlna-renderer/Makefile.am:41: error: HAVE_GSTREAMER_AUDIO does not appear in AM_CONDITIONAL
plugins/dlna-renderer/Makefile.am:46: error: HAVE_LIBXFCE4UI does not appear in AM_CONDITIONAL
plugins/dlna/Makefile.am:41: error: HAVE_GSTREAMER_AUDIO does not appear in AM_CONDITIONAL
plugins/dlna/Makefile.am:46: error: HAVE_LIBXFCE4UI does not appear in AM_CONDITIONAL
plugins/keybinder/Makefile.am:41: error: HAVE_GSTREAMER_AUDIO does not appear in AM_CONDITIONAL
plugins/keybinder/Makefile.am:46: error: HAVE_LIBXFCE4UI does not appear in AM_CONDITIONAL
plugins/lastfm/Makefile.am:40: error: HAVE_GSTREAMER_AUDIO does not appear in AM_CONDITIONAL
plugins/lastfm/Makefile.am:45: error: HAVE_LIBXFCE4UI does not appear in AM_CONDITIONAL
plugins/mpris2/Makefile.am:39: error: HAVE_GSTREAMER_AUDIO does not appear in AM_CONDITIONAL
plugins/mpris2/Makefile.am:44: error: HAVE_LIBXFCE4UI does not appear in AM_CONDITIONAL
plugins/mtp/Makefile.am:45: error: HAVE_GSTREAMER_AUDIO does not appear in AM_CONDITIONAL
plugins/mtp/Makefile.am:50: error: HAVE_LIBXFCE4UI does not appear in AM_CONDITIONAL
plugins/notify/Makefile.am:42: error: HAVE_GSTREAMER_AUDIO does not appear in AM_CONDITIONAL
plugins/notify/Makefile.am:47: error: HAVE_LIBXFCE4UI does not appear in AM_CONDITIONAL
plugins/removable-media/Makefile.am:41: error: HAVE_GSTREAMER_AUDIO does not appear in AM_CONDITIONAL
plugins/removable-media/Makefile.am:46: error: HAVE_LIBXFCE4UI does not appear in AM_CONDITIONAL
plugins/song-info/Makefile.am:51: error: HAVE_GSTREAMER_AUDIO does not appear in AM_CONDITIONAL
plugins/song-info/Makefile.am:56: error: HAVE_LIBXFCE4UI does not appear in AM_CONDITIONAL
plugins/tunein/Makefile.am:40: error: HAVE_GSTREAMER_AUDIO does not appear in AM_CONDITIONAL
plugins/tunein/Makefile.am:45: error: HAVE_LIBXFCE4UI does not appear in AM_CONDITIONAL
src/Makefile.am:110: error: HAVE_GSTREAMER_AUDIO does not appear in AM_CONDITIONAL
src/Makefile.am:115: error: HAVE_LIBXFCE4UI does not appear in AM_CONDITIONAL
src/Makefile.am:120: error: HAVE_PLPARSER does not appear in AM_CONDITIONAL
src/Makefile.am:125: error: HAVE_LIBPEAS does not appear in AM_CONDITIONAL
************************************
(there are also a few warnings: see attached full log)
[AutoreconfFailed.txt](https://github.com/pragha-music-player/pragha/files/673157/AutoreconfFailed.txt)

**Comment by matiasdelellis** [comment]
Please..
Use xfce4-dev-tools...

**Comment by GvMariani** [comment]
I had already installed the package:
giovanni@Gondolin ~/src/pragha (rosa2016.1) $ rpm -qa|grep xfce
xfce4-dev-tools-4.12.0-2-rosa2016.1.x86_64

But the autoreconf stage still fails as described above...

**Comment by matiasdelellis** [comment]
> But the autoreconf stage still fails as described above...

Try ./autogen.sh to use xdt-autogen from xfce4-dev-tools

The configure.ac use some extensions from xfce4-dev-tools.. :wink:

**Comment by GvMariani** [comment]
The last suggestion fixes this issue, but I forgot to report it here... sorry.
Closing.
