### ISSUE TITLE
Update all translations from Transifex

### ISSUE THREAD

**Issue by scootergrisen** [pragha-music-player/pragha#120]
Seems like it 2 years since the translations have last been updated from Transifex.
I have just translated Pragha to danish (da) so i would like to see it included and perhaps changes have been made in the others languages so they properly also want them updated.

**Comment by matiasdelellis** [comment]
HI @scootergrisen ,
Sorry for the delay .. Very busy .. :disappointed: 
Never update them because I intend to merge the WIP/Ampanche branch that will change several strings..

In a few days there will be news .. Thanks!.
