### ISSUE TITLE
Single icon name for tray and app icon

### ISSUE THREAD

**Issue by varlesh** [pragha-music-player/pragha#121]
Will be good use another icon name for tray on Linux systems. It's cool looking with monochrome icons on tray. For example `pragha-panel`.
Thx :)

**Comment by matiasdelellis** [comment]
@varlesh 
Maybe is interesting to do it .. As soon as I finish the WIP/Ampache branch I will continue on other things like this ..

Thank you for always participating .. 😃

**Comment by varlesh** [comment]
If you need help with icon for tray - i can draw.
![2017-07-12 21-31-57](https://user-images.githubusercontent.com/8083855/28130966-913db51e-6749-11e7-864f-ff46d207124b.png)

**Comment by matiasdelellis** [comment]
![pragha-panel-symbolic](https://user-images.githubusercontent.com/733715/28217979-7d61ae02-688d-11e7-8a36-2f952fdb6688.png)
I was trying: :wink:
But I do not know how to make it behave as a symbolic icon in the panel .. 😞

**Comment by matiasdelellis** [comment]
Hi @varlesh 
See las commit..
To use the icon symbolic you must convince the theme designer to add the following:
`
GtkTrayIcon {
   -gtk-icon-style: symbolic;
}
`
... and automatically all system tray icons will be shown symbolic .. 😉 

Thanks for all!.

**Comment by varlesh** [comment]
Thx @matiasdelellis :+1:
