### ISSUE TITLE
Easy to miss dependency on exo

### ISSUE THREAD

**Issue by mgorny** [pragha-music-player/pragha#128]
Hi,

It seems that `exo-csource` is kinda-unconditionally used in Makefiles, e.g.:

```
pragha-window-ui.h: pragha-window.ui Makefile
	$(AM_V_GEN) exo-csource --strip-comments --strip-content --static --name=pragha_window_ui $< > $@
```

Note that due to dep on Makefile, this will be always regenerated. However, `configure` doesn't check for the presence of exo, and I can't grep it anywhere in package sources. Therefore, it is easy to miss the build-time dependency.

**Comment by matiasdelellis** [comment]
@mgorny 
Fixed.. Thank you so much.. 😉
