### ISSUE TITLE
Missing plugin when playing a webradio with TuneIn

### ISSUE THREAD

**Issue by sapristi** [pragha-music-player/pragha#132]
Hello, 
when I launch a webradio added by TuneIn, the player tells me that a gstreamer plugin is missing.
I also wasn't able to launch a webradio (through a link in a m3u for example, loading the m3u doesn't do anything).
I am using gstreamer 1.12 from the arch repo, with all plugins installed.
Do you have any idea of what could be causing this ?

Anyway thanks a lot for this very nice music player !

**Comment by LazyKent** [comment]
I see the same in openSUSE.

**Comment by matiasdelellis** [comment]
Hi..
although it is very probable. Due to the nature of the service, with deprecated api, I can not reproduce this bug. :disappointed: 
Can you give some example of a search? :wink:

**Comment by matiasdelellis** [comment]
Well.. A good alternative?
http://www.radio-browser.info/webservice

:wink:

**Comment by sapristi** [comment]
I tried with various french radios (FIP, canalb, france inter, etc), and none of them work. It seems that TuneIn works : for example with FIP the error says 

`Error playing current track 
(http://opml.radiotime.com/Tune.ashx?id=s15200)
Reason : a plugin is missing in your Gstreamer installation`

Where the given url works in a web browsers and allows me to play the radio. (the error message is roughly translated from French).

**Comment by apps4research** [comment]
I have the same problem ... can you tell us what gstreamer plugin needs is responsible for playing radio streams? If I open the tune.ashx and open the url in my browser the radio stream works, just not in pragha.

**Comment by gftg85** [comment]
> `Error playing current track (http://opml.radiotime.com/Tune.ashx?id=s15200) Reason : a plugin is missing in your Gstreamer installation`

As far as I know, pragha is not able to parse `text/uri-list` links, such as totem can.  Support for playlist parsing in totem is accomplished with routines from the totem-pl-parser library, which pragha could probably use, but I think that this is yet-to-be-implemented.

If you just want to listen to your radio on pragha, you could parse the list by-hand, for instance:

```
$ curl http://opml.radiotime.com/Tune.ashx?id=s15200
http://direct.fipradio.fr/live/fip-midfi.mp3?ID=76zqey582k
http://direct.fipradio.fr/live/fip-lofi.mp3?ID=76zqey582k
```

Just copy one of the URLs above into pragha, instead of the URL you posted.

**Comment by apps4research** [comment]
thanks gftg85, I've done exactly that ... entered the URL in Pragha, but am getting that the error message that a GStreamer plugin is missing, even though I have them all installed ...

**Comment by gftg85** [comment]
I see from your screenshot that you are still trying to play a playlist, which is going to fail for the reason I explained above.

For your case, you would also have to parse the URL by-hand, like this:

```
$ curl http://mp3-live.swr.de/swr1bw_m.m3u
#EXTM3U
#EXTINF:-1,SWR1 Baden-Württemberg
http://swr-swr1-bw.cast.addradio.de/swr/swr1/bw/mp3/128/stream.mp3
```

Then copy the URL above into pragha.  It worked for me on Debian.

**Comment by gftg85** [comment]
It would be very nice if pragha had support for parsing playlists...  I currently don't know how to implement it, but I might give it a try.

**Comment by apps4research** [comment]
Ahh! yes, I undestand now, thanks so much, its working now :) Really appreciate your patience :)

**Comment by gftg85** [comment]
Cheers!  Nice radio, by the way. :)

**Comment by apps4research** [comment]
> It would be very nice if pragha had support for parsing playlists... I currently don't know how to implement it, but I might give it a try.

Agreed btw, would be cool if you do decide to give it a go. Am liking pragha very much (more than rhytmbox, which was getting on my nerves), and think it has a lot of potential ...

**Comment by matiasdelellis** [comment]
Hi all,
Can you tell me exactly what terms you are using to search? So I try to reproduce it. :smile:

**Comment by matiasdelellis** [comment]
However I suspect that this can help ..
https://github.com/pragha-music-player/pragha/commit/68377e99528e4e8fe7cce02329aaeb805af49c5d

**Comment by matiasdelellis** [comment]
OK.. Searching FIP, the first item is 'audio' but it is a playlist.. :disappointed: 

> http://opml.radiotime.com/Search.aspx?query=FIP

The shared commit in this case no help, and may be more difficult to fix..

**Comment by matiasdelellis** [comment]
Hi all,

>  and may be more difficult to fix..

Rectify ... it's really implemented, but depend to compile Pragha with totem-pl-parser..

**Comment by gftg85** [comment]
>Rectify ... it's really implemented, but depend to compile Pragha with totem-pl-parser

Indeed.  I'll fix it for the next pragha release on Debian, which must wait for Debian's code freeze, so I'll write back in a month or so.

**Comment by gftg85** [comment]
Thanks for closing the bug report.

For those using Debian... The new Debian build, 1.3.4-1, which has support for playlist parsing, is currently available on Debian unstable/sid (and will likely migrate to Debian testing/bullseye in 3 days, if I didn't screw anything up).  The versions in each Debian release can be found [here](https://tracker.debian.org/pkg/pragha).
