### ISSUE TITLE
64bit portability issue

### ISSUE THREAD

**Issue by LazyKent** [pragha-music-player/pragha#137]
Compile Pragha v.1.4 (Beta 2.1) in openSUSE.

Buildlog checker detects an error:
`E: pragha 64bit-portability-issue pragha.h:55`

Looking at the log file I see:
```
 In file included from pragha-menubar.h:25:0,
                  from pragha-playlist.c:34:
 pragha.h:55:36: warning: passing argument 2 of 'g_slist_append' makes pointer from integer without a cast [-Wint-conversion]
```

**Comment by matiasdelellis** [comment]
Hi @LazyKent 
I think it's fixed with the last commit. I leave it open until the next release, or until you check it.

Regards,
Thanks for all.. :smile:

**Comment by LazyKent** [comment]
Fixed, closed.
