### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by LazyKent** [pragha-music-player/pragha#141]
I see untranslated words in the the interface: Title, Artist, Album, etc.
I've translated the whole ru.po in Transifex (and locally for testing). But can't find those strings for translation.
[Screen](http://susepaste.org/view/simple/66784766)

**Comment by matiasdelellis** [comment]
Ohh..
I have to synchronize better with transifex .. :disappointed:

**Comment by matiasdelellis** [comment]
Hi @LazyKent 
Update all translation from transifex.. Thanks.. :wink:
