### ISSUE TITLE
Search similar words doesn't find Irish song titles

### ISSUE THREAD

**Issue by kalikiana** [pragha-music-player/pragha#146]
It would be great if I could type `Óró sé do bheatha 'bhaile` by just typing `oro` without worrying about the diactrics. In technical terms the search would need to find words by their canonicalized unicode characters.

**Comment by matiasdelellis** [comment]
Hi @kalikiana 
There is an option for "Search similar words", clicking on the magnifying glass of search entry.

Today it is quite rigid since it uses levenshtein distance up to 1 character.. and in the proposed case it should work.. :wink:

**Comment by matiasdelellis** [comment]
p.s: I'm seeing you continue with Midori .. I'm very happy !! :smiley:

**Comment by kalikiana** [comment]
> There is an option for "Search similar words", clicking on the magnifying glass of search entry.
> 
> Today it is quite rigid since it uses levenshtein distance up to 1 character.. and in the proposed case it should work.. wink

Hmmm so I enabled that option and it works in most cases like `Jö schau`, `Pokëmon`, `Ill Niño` or `Zé Glisse`, but **not** for `Óró sé do bheatha 'bhail`

**Comment by matiasdelellis** [comment]
Hi @kalikiana 
Can you test the last commit?. (If you use 1.3, you can apply the patch cleanly).
Thanks, and sorry for the delay ..
