### ISSUE TITLE
slow startup!

### ISSUE THREAD

**Issue by Unixware** [pragha-music-player/pragha#168]
Hello.

the program takes about 20-30sec to start! thats on debian sid   (pragha v 1.3.4)
on my tests on other OS -NetBSD- starts almost instantly.
Known bug ? I ve tried the "-e 4" no logs at all! 

only one error : 
`(pragha:393111): Gtk-WARNING **: 23:49:20.769: Rescan library: missing action Rescan library`

is there anyway to debug this?

thanks

**Comment by Unixware** [comment]
dbus fuckup ... nothing to do with this program -SOLVED

**Comment by inconstante** [comment]
Thanks for the followup. :)
