### ISSUE TITLE
Global Hotkey Support

### ISSUE THREAD

**Issue by bwat47** [pragha-music-player/pragha#35]
Pragha is a wonderful, fast player but it seems to have no support for media keys or any kind of hotkeys. This is a dealbreaker for me and I'd love to see support added.
##

**Comment by kalikiana** [comment]
What's the status of this? With Pragha 1.3.3 under GNOME 3.28.3 (Wayland) they don't work for me where other apps do.

**Comment by matiasdelellis** [comment]
Hi @kalikiana 
gnome-media-keys is deprecated on gnome3... But you can control Pragha with mpris2. Activate this in preferences.

**Comment by kalikiana** [comment]
@matiasdelellis Activate where? Pragha has no such preference as far as I can see

**Comment by kalikiana** [comment]
It seems like the Ubuntu package doesn't install any plugins. Latest master built from source, **and installed**, has an MPRIS plugin that works!

**Comment by matiasdelellis** [comment]
Great! :smile:
