### ISSUE TITLE
add support for tracker music ( xm, mod, sid, .. )

### ISSUE THREAD

**Issue by ghost** [pragha-music-player/pragha#58]
afaik most of them are already supported in gstreamer via the modplug plugin. would be greatly appreciated ;)

**Comment by wymiatacz** [comment]
Hi,
May I ask what is the reason for maintaining white lists of MIME types in the application instead of relying on libraries and simply accepting all audio/* & video/* ?
For example, pragha lacks support for audio/aac, audio/mp2 or audio/mp4 despite GStreamer can play that.
