### ISSUE TITLE
Untranslated strings in Russian

### ISSUE THREAD

**Issue by LazyKent** [pragha-music-player/pragha#75]
I see some untranslated strings in Russian Pragha v1.3.2 interface.
I have translated almost all the strings to Russian (except the one I don't understand well and haven't tested).

Please, have a look at http://susepaste.org/view/simple/72583104

And "Settings — Plugins" tab isn't translated at all.
Thanks.
##

**Comment by matiasdelellis** [comment]
"Settings — Plugins" I think is fixed on transifex.. The string in the about dialog never was put to translations.

Then I see if it's worth adding it or change it to another string..

Thanks for all,
Regards.
