### ISSUE TITLE
Not save state album_art_in_osd=false

### ISSUE THREAD

**Issue by varlesh** [pragha-music-player/pragha#77]
Album art disabled, but after restart show again.
Ubuntu 14.04
Pragha 1.3.2

**Comment by Sidorr** [comment]
+1

**Comment by Senpos** [comment]
same thing

**Comment by matiasdelellis** [comment]
Hi,
Sorry for the delay,
I never saw your comments.. Now check it.. :wink:

**Comment by matiasdelellis** [comment]
Fix commited,
Next week maybe release a new micro version. :smile:

Regards,
Thanks for the report!.

**Comment by varlesh** [comment]
Thank you ))

**Comment by flexo3001** [comment]
Same problem seems to exist for show_album_art=true. Tried to change in the config-file and after starting it was overritten. 
Version: 1.3.2.1
OS: Archlinux

**Comment by matiasdelellis** [comment]
Hi @flexo3001 
You're right, still not released the version with the necessary changes.. I hope to do this week.. 

But please, I invite you to build from git and test it.. :wink:

**Comment by matiasdelellis** [comment]
Fixed on last version =)

Please, test and close it.. 

Thanks for all,
Regards,
Matias
