### ISSUE TITLE
lyrics problem

### ISSUE THREAD

**Issue by varlesh** [pragha-music-player/pragha#78]
Russian locale.
Ubuntu 14.04
Pragha 1.3.2.1
English lyrics info not correct show (only lyricswiki)
![2015-04-03 01 26 28](https://cloud.githubusercontent.com/assets/8083855/6975087/0a97ddc4-d9a1-11e4-9ae1-a70378fd64bb.png)
Russian lyrics show correct, but long search - more 1 min.

**Comment by Sidorr** [comment]
+1

**Comment by matiasdelellis** [comment]
Hi,
Sorry for the delay,
I never saw your comments

It is a bug of gylr that is fixed at its last version.. :wink: 

https://github.com/sahib/glyr/commit/530e91963221eb299e6b123e7fdb4a692cc689e0

Regards,
Matias

**Comment by varlesh** [comment]
I install libglyr1 1.0.8-1 from https://packages.debian.org/experimental/libglyr1
lyricswiki working fine.

**Comment by matiasdelellis** [comment]
Ok..
Close it.. :wink: 

Regards,
