### ISSUE TITLE
Add glyr library for depends

### ISSUE THREAD

**Issue by varlesh** [pragha-music-player/pragha#84]
Song Info use glyr plugin, but it is not specified on README.
PS: on Arch Linux this plugin not avaiable :(

**Comment by matiasdelellis** [comment]
Hi,

> Song Info use glyr plugin, but it is not specified on README.

Well, In the README file do not specify any dependencies for plugins.. (Even for the cdrom that before was required).. Just libpeas that enable plugin support.

Maybe I can add a INSTALL file to document it better.. and also have pending write a good wiki to write everything.

> PS: on Arch Linux this plugin not avaiable :(

Sorry. I do not maintain the Arch package, please declare a bug on Arch bugtracker.. :wink: 

Regards,
Thanks for all.

**Comment by varlesh** [comment]
Hi :) Ok, add to INSTALL.
I already create bug report:
https://bugs.archlinux.org/task/46421?project=5&cat[0]=33&string=pragha

**Comment by matiasdelellis** [comment]
Thanks.. :grin:
