### ISSUE TITLE
Menu icon blured

### ISSUE THREAD

**Issue by varlesh** [pragha-music-player/pragha#85]
fallbacks_icon_menu use open-menu-symbolic.
This not good variant, because other icons not symbolic (different style and color) and symbolic icons one size only (16x16px), but player have option use 24x24 icons and 16x16.
When you use 24x24 px icons on toolbar (disable option "Use small icons") menu icon blured.
Maybe better use other icon, not symbolic?
![2015-09-25 21-04-52](https://cloud.githubusercontent.com/assets/8083855/10108447/9ba30c1e-63c9-11e5-95b1-8de675dfe195.png)
![2015-09-25 21-04-17](https://cloud.githubusercontent.com/assets/8083855/10108446/9ba16f8a-63c9-11e5-9efa-6f9dad611f4c.png)

**Comment by varlesh** [comment]
open-menu good variant. But Adwaita not have this icon. 
Icons are by preference. Maybe use open-menu as default, open-menu-symbolic use as second?
```
const gchar *fallbacks_icon_menu[] = {
		"open-menu",
		"open-menu-symbolic",
		"emblem-system-symbolic",
		"emblem-system",
		NULL,
	};
```

**Comment by matiasdelellis** [comment]
Please, test and close.. :wink:

p.s:. change sizes of icons, are not a feature. I did it to fix the icons with CSD.. haha.. :disappointed:

**Comment by varlesh** [comment]
thx :wink:
