### ISSUE TITLE
Last.fm plugin ?

### ISSUE THREAD

**Issue by siSSSou** [pragha-music-player/pragha#92]
Installed Pragha 1.3.3 on Xubuntu 15.10 with ppa:ubuntuhandbook1/pragha
Excellent audio player but with one problem : there's no Last.fm plugin available !

-> Did I miss anything ?
-> Any dependency ?
-> Something else ?

**Comment by siSSSou** [comment]
This version is built without libclastfm0.
To get Pragha working with lastfm plugin on ubuntu 15.10, getdeb can be used : http://www.getdeb.net/welcome/
It works like a charm ;-)

**Comment by matiasdelellis** [comment]
Ok..
Sorry the delay.. Thanks to participate here..

So, close it... :wink:
