### ISSUE TITLE
Last.fm suggested a tag correction for Russian tags

### ISSUE THREAD

**Issue by LazyKent** [pragha-music-player/pragha#93]
Last.fm suggested a tag correction for Russian tags.

And it looks very strange:
http://susepaste.org/view/simple/39258450

The tags are OK:
http://susepaste.org/view/simple/76559656

Not seen with OGG files only. The same with MP3:
http://susepaste.org/view/simple/56311010

Is this something wrong in libclastfm or in Pragha itself?
##

**Comment by matiasdelellis** [comment]
Hi @LazyKent 
Sorry the delay in answering.

> Last.fm suggested a tag correction for Russian tags.

Surely this is a mistake of the library managing utf8/unicode.. Please send me the tags of an entire song to do some tests..

**Comment by LazyKent** [comment]
Hello. The tags are:
```
Album                                    : Откровение
Track name                               : Танец с саблями
Track name/Position                      : 02
Performer                                : Валерий Ковтун
Genre                                    : Instrumental
Recorded date                            : 2007
```

**Comment by matiasdelellis** [comment]
Hi, 
You can reproduce the bug .. Now I do a couple of tests ..;)

p.d: Mabybe related to https://github.com/pragha-music-player/pragha/issues/28 ?

**Comment by matiasdelellis** [comment]
Hi @LazyKent,
Seems to be an error on last.fm API.. The error appears whenever that send characters outside the ASCII.. Not only in Russian, also with accents in Spanish..

I Still not yet discover the encoding used by lastfm to return data..

**Comment by matiasdelellis** [comment]
Still today I do not see how to solve this .. .. :disappointed:

**Comment by matiasdelellis** [comment]
Hi @LazyKent 
If you feel like completing the Russian alphabet, welcome ... :wink: 

ps.: Far from being efficient, at least it is only used in a thread separated from the main one.. :sweat_smile:

**Comment by LazyKent** [comment]
At the moment I don't see any warnings from Last.fm to Russian tags.
Probably, fixed there.
Closed.
