### ISSUE TITLE
Unable to view playback controls

### ISSUE THREAD

**Issue by PhillipMwaniki** [pragha-music-player/pragha#96]
I am running Linux mint 17.3 and I am unable to view the playback controls even if I click on the toggle option on the view menu

**Comment by matiasdelellis** [comment]
Hi, @PhillipMwaniki,
Thanks for the report!.

There is no option to hide the playback controls.. But there are the option of placing them below (On the menu), or hide the window border (On preferences dialog).

Please check these settings. :wink: 
Also check that launching Pragha in a terminal no report any error...

Finally, try playing with the gtk inspector (CTRL+MAYUS+I). Search within the elements PraghaToolbar and see if this well constructed..

Regards,
Matias

**Comment by matiasdelellis** [comment]
p.s: Gtk Version???

**Comment by matiasdelellis** [comment]
Hi @PhillipMwaniki 
Any news on it? Plese test it and send me info..
