### ISSUE TITLE
How to setting mpd for remote control Pragha player?

### ISSUE THREAD

**Issue by dimti** [pragha-music-player/pragha#99]
Hello

I use xfce4 and desktop mdp widget
Some time ago Pragha available to use mpd widget for control pragha player.
But today is not work (long long time not work) and i not understant what is mpd and how to debug this.

1. Pragha support mpd?
2. if yes, how i can debug that for solve my local problem?

**Comment by matiasdelellis** [comment]
Hi,
> Pragha support mpd?
No.. Pragha implement default MPRIS2 interface... (It is a plugin, remember enabled it)I guess the widget use this to control Pragha.

**Comment by dimti** [comment]
I installed from aur - xfce4-soundmenu-plugin. Works
